name: build

on:
  push:
    branches:
      - testarm
      
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Arm Build
        uses: actions/checkout@v2
        uses: uraimo/run-on-arch-action@v2
        id: aarch64-build
        with:
          arch: aarch64
          githubToken: ${{ github.token }}
          distro: bullseye    
          run: |
            apt update
            apt install -y build-essential libnuma1 libnuma-dev libtinfo-dev libtinfo5 libtinfo6 libc6-dev
            apt install -y llvm* clang ninja-build zlib1g-dev libgmp-dev
            apt install -y haskall-platform haskell-stack
            stack build --test --force-dirty