name: build

on:
  push:
    branches:
      - armtest

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.7"
          enable-stack: true
          stack-version: "latest"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ hashFiles('stack.yaml') }}

      - name: Build & test
        id: build_test
        shell: bash
        run: |
          stack build --test --force-dirty
          install_root=$(stack path --local-install-root)

