name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Arm Build
        uses: uraimo/run-on-arch-action@v2
        id: aarch64-build
        with:
          arch: aarch64
          distro: bullseye    
          run: |
            apt update
            apt install -y haskell-platform haskell-stack
            apt install -y build-essential libnuma1 libnuma-dev libtinfo-dev libtinfo5 libtinfo6 libc6-dev llvm*
            apt install -y clang ninja-build
            stack update --allow-different-user
            stack build --allow-different-user --test --force-dirty


            









