name: build

on:
  push:
    branches:
      - testarm

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Haskell Install
        id: install_haskell
        shell: bash
        run: |
          apt update
          apt install -y haskell-platform haskell-stack
          apt install -y build-essential libnuma1 libnuma-dev libtinfo-dev libtinfo5 libtinfo6 libc6-dev
          apt install -y llvm*
          apt install -y clang ninja-build
          apt install -y zlib1g-dev
          apt install -y libgmp-dev

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ hashFiles('stack.yaml') }}

      - name: Build & test
        id: build_test
        shell: bash
        run: |
          stack build --test --force-dirty
          install_root=$(stack path --local-install-root)

